"""YAML workflow generation from LLM output"""
import yaml
from typing import Dict, Any, Optional
from src.models.types import GeneratedWorkflow
from src.components.llm_client import GroqLLMClient

class YAMLGenerator:
    """Generate and manage YAML workflows"""
    
    def __init__(self, llm_client: GroqLLMClient):
        self.llm_client = llm_client
    
    def generate_from_prompt(self, prompt: str) -> GeneratedWorkflow:
        """Generate YAML from a detailed prompt"""
        yaml_content = self.llm_client.generate_workflow_yaml(prompt)
        yaml_content = self._sanitize_llm_yaml(yaml_content)
        
        workflow = GeneratedWorkflow(
            yaml_content=yaml_content,
            metadata={"generation_method": "llm"},
            is_valid=False,
            attempts=1,
        )
        
        return workflow

    def _sanitize_llm_yaml(self, raw_output: str) -> str:
        """Strip markdown wrappers and normalize raw LLM YAML output."""
        if not raw_output:
            return raw_output

        cleaned = raw_output.strip()

        lines = [line for line in cleaned.splitlines() if not line.strip().startswith("```")]
        cleaned = "\n".join(lines).strip()

        if cleaned.lower().startswith("yaml\n"):
            cleaned = cleaned[5:]
        elif cleaned.lower().startswith("yml\n"):
            cleaned = cleaned[4:]

        yaml_start_keys = ("name:", "on:", "jobs:", "permissions:", "env:")
        cleaned_lines = cleaned.splitlines()
        start_index = 0
        for index, line in enumerate(cleaned_lines):
            if line.strip().lower().startswith(yaml_start_keys):
                start_index = index
                break
        candidate_lines = cleaned_lines[start_index:]

        trimmed_lines = []
        for line in candidate_lines:
            stripped = line.strip()
            if stripped and not line.startswith((" ", "\t", "-", "#")) and ":" not in line:
                break
            trimmed_lines.append(line)

        cleaned = "\n".join(trimmed_lines).strip()

        return cleaned.strip()
    
    def parse_yaml(self, yaml_content: str) -> Optional[Dict[str, Any]]:
        """Parse YAML content"""
        yaml_content = self._sanitize_llm_yaml(yaml_content)
        try:
            parsed = yaml.safe_load(yaml_content)
            if isinstance(parsed, dict) and True in parsed and 'on' not in parsed:
                parsed['on'] = parsed.pop(True)
            return parsed
        except yaml.YAMLError as e:
            print(f"YAML parsing error: {e}")
            return None
    
    def validate_yaml_syntax(self, yaml_content: str) -> tuple[bool, Optional[str]]:
        """Validate YAML syntax"""
        yaml_content = self._sanitize_llm_yaml(yaml_content)
        try:
            yaml.safe_load(yaml_content)
            return True, None
        except yaml.YAMLError as e:
            return False, str(e)
    
    def format_yaml(self, data: Dict[str, Any], width: int = 120) -> str:
        """Format dictionary as pretty YAML"""
        return yaml.dump(
            data,
            default_flow_style=False,
            sort_keys=False,
            width=width,
            allow_unicode=True,
        )
    
    def merge_yaml_configs(self, base_yaml: Dict[str, Any], overrides: Dict[str, Any]) -> Dict[str, Any]:
        """Merge two YAML configurations"""
        merged = base_yaml.copy()
        
        for key, value in overrides.items():
            if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
                merged[key] = self.merge_yaml_configs(merged[key], value)
            else:
                merged[key] = value
        
        return merged
    
    def add_metadata(self, yaml_content: str, metadata: Dict[str, Any]) -> str:
        """Add metadata comments to YAML"""
        lines = yaml_content.split('\n')
        
        # Add header comment
        header = ['# GitHub Actions Workflow', '# Auto-generated by CI/CD Agent', '#']
        header.append(f"# Generated: {metadata.get('generated_at', 'Unknown')}")
        
        if metadata.get('description'):
            header.append(f"# Description: {metadata['description']}")
        
        header.append('#\n')
        
        return '\n'.join(header) + '\n' + yaml_content
    
    def extract_jobs(self, parsed_yaml: Dict[str, Any]) -> Dict[str, Any]:
        """Extract jobs from parsed YAML"""
        return parsed_yaml.get('jobs', {})
    
    def validate_required_fields(self, parsed_yaml: Dict[str, Any]) -> tuple[bool, list[str]]:
        """Validate required YAML fields"""
        errors = []

        if True in parsed_yaml and 'on' not in parsed_yaml:
            parsed_yaml['on'] = parsed_yaml.pop(True)
        
        if 'name' not in parsed_yaml:
            errors.append("Missing required field: 'name'")
        if 'on' not in parsed_yaml:
            errors.append("Missing required field: 'on'")
        if 'jobs' not in parsed_yaml:
            errors.append("Missing required field: 'jobs'")
        
        jobs = parsed_yaml.get('jobs', {})
        if not jobs:
            errors.append("At least one job is required")
        
        for job_name, job_config in jobs.items():
            if not isinstance(job_config, dict):
                errors.append(f"Job '{job_name}' must be an object")
                continue
            
            if 'runs-on' not in job_config and 'runs-on' not in parsed_yaml:
                errors.append(f"Job '{job_name}' missing 'runs-on'")
            
            if 'steps' not in job_config:
                errors.append(f"Job '{job_name}' missing 'steps'")
        
        return len(errors) == 0, errors
    
    def auto_fix_common_issues(self, yaml_content: str) -> str:
        """Attempt to auto-fix common YAML issues"""
        parsed = self.parse_yaml(yaml_content)
        
        if not parsed:
            return yaml_content
        
        # Fix common issues
        if isinstance(parsed.get('on'), str):
            parsed['on'] = [parsed['on']]
        
        # Ensure jobs have required fields
        for job_name, job_config in parsed.get('jobs', {}).items():
            if 'runs-on' not in job_config:
                job_config['runs-on'] = 'ubuntu-latest'
            
            if 'steps' in job_config and isinstance(job_config['steps'], list):
                for i, step in enumerate(job_config['steps']):
                    if isinstance(step, dict):
                        if 'name' not in step and 'uses' in step:
                            step['name'] = f"Step {i+1}"
        
        return self.format_yaml(parsed)
