from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional
from uuid import uuid4

from fastapi import Body, FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from backend.orchestrator_utils import (
    _parse_orchestrator_stdout,
    build_launch_env,
    extract_artifacts,
)
from backend.websocket_manager import RunManager, RunState


class RunRequest(BaseModel):
    prompt: str
    repo_path: Optional[str] = None
    github_url: Optional[str] = None
    require_plan_approval: bool = False
    create_pr: bool = False
    branch_name: Optional[str] = None
    pr_title: Optional[str] = None
    pr_body: Optional[str] = None
    output_scope: Literal["asked", "all"] = "asked"
    runtime_secrets: Dict[str, str] = Field(default_factory=dict)


class ApproveRequest(BaseModel):
    approved: bool
    edited_execution_order: List[Any] = Field(default_factory=list)


app = FastAPI(title="Orchestrator Backend", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:4200"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ORCHESTRATOR_SCRIPT = PROJECT_ROOT / "test_pfe" / "02-orchestration-agents-layer" / "orchestrator-agent" / "run_orchestrator.py"
ORCHESTRATOR_CWD = ORCHESTRATOR_SCRIPT.parent
SIGNAL_DIR = ORCHESTRATOR_CWD  # Directory for approval/repair signal files

run_manager = RunManager()
runs: Dict[str, RunState] = run_manager.runs


def _build_orchestrator_command(payload: RunRequest, run_id: str) -> List[str]:
    print(f"[Backend] DEBUG: require_plan_approval = {payload.require_plan_approval}", file=sys.stderr)
    cmd = [sys.executable, "-u", str(ORCHESTRATOR_SCRIPT)]
    cmd.extend(["--prompt", payload.prompt])
    cmd.extend(["--run-id", run_id])

    # Pass run_id via environment variable as backup
    # (command-line arg should work, but this is a safety net)

    if payload.require_plan_approval:
        print(f"[Backend] Adding --plan-only flag", file=sys.stderr)
        cmd.append("--plan-only")
    else:
        print(f"[Backend] NOT adding --plan-only flag", file=sys.stderr)

    if payload.repo_path:
        cmd.extend(["--repo-path", payload.repo_path])

    if payload.github_url:
        cmd.extend(["--github-url", payload.github_url])

    cmd.extend(["--output-scope", payload.output_scope])

    user_feedback = "accept" if payload.create_pr else "not"
    cmd.extend(["--user-feedback", user_feedback])

    if payload.create_pr:
        branch_name = str(payload.branch_name or "").strip() or "devops/auto-generated"
        pr_title = str(payload.pr_title or "").strip() or "Auto-generated DevOps configurations"
        pr_body = str(payload.pr_body or "").strip() or "Generated by Multi-Agent DevOps Orchestrator"
        cmd.append("--create-pr")
        cmd.extend(["--branch-name", branch_name])
        cmd.extend(["--pr-title", pr_title])
        cmd.extend(["--pr-body", pr_body])

    return cmd


def _ensure_run_exists(run_id: str) -> RunState:
    run_state = run_manager.get_run(run_id)
    if run_state is None:
        raise HTTPException(status_code=404, detail=f"Run not found: {run_id}")
    return run_state


@app.post("/api/runs")
async def start_run(request: RunRequest) -> Dict[str, str]:
    if not request.prompt.strip():
        raise HTTPException(status_code=400, detail="prompt is required")

    if not ORCHESTRATOR_SCRIPT.exists():
        raise HTTPException(status_code=500, detail=f"Orchestrator script not found: {ORCHESTRATOR_SCRIPT}")

    run_id = str(uuid4())
    cmd = _build_orchestrator_command(request, run_id)
    run_env = build_launch_env(os.environ.copy(), request.runtime_secrets)
    run_env.setdefault("PYTHONUNBUFFERED", "1")
    run_env.setdefault("PYTHONIOENCODING", "utf-8")
    # Pass run_id via environment variable as backup
    run_env["ORCHESTRATOR_RUN_ID"] = run_id
    run_manager.start_run(
        run_id=run_id,
        cmd=cmd,
        cwd=str(ORCHESTRATOR_CWD),
        env=run_env,
    )

    return {"run_id": run_id}


@app.websocket("/ws/runs/{run_id}")
async def stream_run_logs(websocket: WebSocket, run_id: str) -> None:
    await websocket.accept()

    run_state = run_manager.get_run(run_id)
    if run_state is None:
        await websocket.send_json({"type": "error", "message": f"Run not found: {run_id}"})
        await websocket.close(code=1008)
        return

    line_index = 0
    try:
        while True:
            new_lines = run_manager.get_new_lines(run_id, line_index)
            if new_lines:
                for line in new_lines:
                    await websocket.send_json({"type": "log", "line": line})
                line_index += len(new_lines)

            if not run_manager.is_running(run_id):
                run_state = _ensure_run_exists(run_id)
                if run_state.parsed_result is None:
                    stdout_text = "\n".join(run_state.output_lines)
                    run_state.parsed_result = _parse_orchestrator_stdout(stdout_text, "")

                run_state.returncode = (
                    run_state.process.returncode
                    if run_state.process.returncode is not None
                    else run_state.process.poll()
                )

                await websocket.send_json({"type": "complete", "result": run_state.parsed_result})
                await websocket.close()
                return

            await asyncio.sleep(0.1)
    except WebSocketDisconnect:
        return


@app.get("/api/runs/{run_id}/status")
async def get_run_status(run_id: str) -> Dict[str, Any]:
    run_state = _ensure_run_exists(run_id)
    running = run_manager.is_running(run_id)
    returncode = run_state.process.returncode if run_state.process.returncode is not None else run_state.process.poll()
    run_state.returncode = returncode

    return {
        "run_id": run_id,
        "running": running,
        "returncode": returncode,
        "line_count": len(run_state.output_lines),
    }


@app.post("/api/runs/{run_id}/approve")
async def approve_run(run_id: str, request: ApproveRequest) -> Dict[str, Any]:
    _ensure_run_exists(run_id)
    
    # Ensure signal directory exists
    SIGNAL_DIR.mkdir(parents=True, exist_ok=True)
    print(f"[Backend] Signal directory: {SIGNAL_DIR.resolve()}", file=sys.stderr)
    print(f"[Backend] Signal directory exists: {SIGNAL_DIR.exists()}", file=sys.stderr)
    
    approval_file = SIGNAL_DIR / f"{run_id}.approval.json"
    payload = {
        "run_id": run_id,
        "approved": request.approved,
        "edited_execution_order": request.edited_execution_order,
        "timestamp": time.time(),
    }
    
    try:
        approval_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print(f"[Backend] ✅ Approval signal written to: {approval_file.resolve()}", file=sys.stderr)
        print(f"[Backend] File exists: {approval_file.exists()}", file=sys.stderr)
        print(f"[Backend] Signal content: {json.dumps(payload, indent=2)}", file=sys.stderr)
        sys.stderr.flush()
    except Exception as e:
        print(f"[Backend] ❌ ERROR writing approval signal: {e}", file=sys.stderr)
        sys.stderr.flush()
        raise
    
    return {"ok": True, "file": str(approval_file)}


@app.post("/api/runs/{run_id}/repair")
async def request_repair(run_id: str, payload: Dict[str, Any] = Body(default_factory=dict)) -> Dict[str, Any]:
    _ensure_run_exists(run_id)
    repair_file = ORCHESTRATOR_CWD / f"{run_id}.repair.json"
    repair_payload = {
        "run_id": run_id,
        "timestamp": time.time(),
        **(payload or {}),
    }
    repair_file.write_text(json.dumps(repair_payload, indent=2), encoding="utf-8")
    return {"ok": True, "file": str(repair_file)}


@app.get("/api/runs/{run_id}/debug")
async def debug_run(run_id: str) -> Dict[str, Any]:
    """Debug endpoint: shows raw stored lines and what the parser sees."""
    run_state = _ensure_run_exists(run_id)
    total_lines = len(run_state.output_lines)
    # Show last 30 lines so we can see the JSON block
    tail = run_state.output_lines[max(0, total_lines - 30):]
    stdout_text = "\n".join(run_state.output_lines)
    parsed = _parse_orchestrator_stdout(stdout_text, "")
    return {
        "run_id": run_id,
        "total_lines": total_lines,
        "tail_lines": tail,
        "parsed_status": parsed.get("status"),
        "has_state": "state" in parsed,
        "has_agent_outputs": bool(parsed.get("state", {}).get("agent_outputs")),
        "parsed_result_cached": run_state.parsed_result is not None,
    }


@app.get("/api/runs/{run_id}/artifacts")
async def get_artifacts(run_id: str) -> Dict[str, Any]:
    run_state = _ensure_run_exists(run_id)

    stdout_text = "\n".join(run_state.output_lines)
    # Always re-parse to pick up latest output (handles race between process exit and HTTP call)
    run_state.parsed_result = _parse_orchestrator_stdout(stdout_text, "")

    print(f"[Backend] artifacts: total_lines={len(run_state.output_lines)}, has_state={'state' in run_state.parsed_result}, has_agent_outputs={bool(run_state.parsed_result.get('state', {}).get('agent_outputs'))}", file=sys.stderr)
    sys.stderr.flush()

    return extract_artifacts(run_state.parsed_result)


@app.get("/api/runs/{run_id}/plan")
async def get_execution_plan(run_id: str) -> Dict[str, Any]:
    run_state = _ensure_run_exists(run_id)

    if run_state.parsed_result is None:
        stdout_text = "\n".join(run_state.output_lines)
        run_state.parsed_result = _parse_orchestrator_stdout(stdout_text, "")

    result = run_state.parsed_result or {}
    plan = result.get("execution_plan", {})
    
    return {
        "run_id": run_id,
        "plan": plan,
        "complexity_score": result.get("complexity_score", 0),
        "planner_reasoning": result.get("planner_reasoning", ""),
        "status": result.get("status", "unknown"),
        "plan_only": result.get("plan_only", False),
    }


@app.get("/api/runs/{run_id}/logs")
async def get_logs(
    run_id: str,
    offset: int = 0,
    limit: int = 100,
) -> Dict[str, Any]:
    run_state = _ensure_run_exists(run_id)
    
    all_lines = run_state.output_lines
    total = len(all_lines)
    lines = all_lines[offset : offset + limit] if offset < total else []
    
    return {
        "run_id": run_id,
        "lines": lines,
        "offset": offset,
        "limit": limit,
        "total": total,
        "has_more": offset + limit < total,
    }


@app.post("/api/runs/{run_id}/cancel")
async def cancel_run(run_id: str) -> Dict[str, Any]:
    run_state = _ensure_run_exists(run_id)
    
    if run_state.process and run_state.process.poll() is None:
        run_state.process.terminate()
        try:
            run_state.process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            run_state.process.kill()
    
    return {"ok": True, "run_id": run_id}
