"""
LangGraph Orchestrator - Graph Construction and Compilation.

This module builds the orchestration graph matching the requested architecture:
user prompt -> guardrails -> repo-analysis -> (complex ? planner path : direct routing path)
"""

from typing import Literal
from langgraph.graph import StateGraph, START, END

from .graph_state import OrchestratorState, create_initial_state, state_to_legacy_format
from .graph_nodes import (
    guardrails_node,
    repo_analysis_node,
    complexity_assessment_node,
    planner_node,
    man_in_the_loop_node,
    plan_confirmed_node,
    dag_execution_node,
    routing_direct_node,
    agent_execution_node,
    user_feedback_node,
    create_pr_node,
    cleanup_node,
    initialize_components,
)


def should_continue_after_guardrails(state: OrchestratorState) -> Literal["repo_analysis", "cleanup"]:
    if state.get("guardrails_passed", False):
        return "repo_analysis"
    return "cleanup"


def should_use_planner_path(state: OrchestratorState) -> Literal["planner", "routing_direct"]:
    return "planner" if state.get("used_planner", False) else "routing_direct"


def should_continue_after_man_in_the_loop(state: OrchestratorState) -> Literal["plan_confirmed", "cleanup"]:
    if state.get("status") == "error":
        return "cleanup"
    return "plan_confirmed" if state.get("plan_approved", False) else "cleanup"


def should_create_pr_after_feedback(state: OrchestratorState) -> Literal["create_pr", "cleanup"]:
    feedback = (state.get("user_feedback") or "accept").lower()
    if state.get("create_pr", False) and feedback == "accept":
        return "create_pr"
    return "cleanup"


def build_orchestrator_graph() -> StateGraph:
    """
    Build the LangGraph orchestrator graph.

    Requested shape:
    START -> guardrails -> repo_analysis -> complexity_assessment
      complex -> planner -> man_in_the_loop -> (approved ? plan_confirmed -> dag_execution -> execution : cleanup)
      not-complex -> routing_direct
      execution/routing_direct -> user_feedback -> (accept+create_pr ? create_pr : cleanup) -> END
    """
    initialize_components()

    graph = StateGraph(OrchestratorState)

    graph.add_node("guardrails", guardrails_node)
    graph.add_node("repo_analysis", repo_analysis_node)
    graph.add_node("complexity_assessment", complexity_assessment_node)
    graph.add_node("planner", planner_node)
    graph.add_node("man_in_the_loop", man_in_the_loop_node)
    graph.add_node("plan_confirmed", plan_confirmed_node)
    graph.add_node("dag_execution", dag_execution_node)
    graph.add_node("routing_direct", routing_direct_node)
    graph.add_node("execution", agent_execution_node)
    graph.add_node("user_feedback", user_feedback_node)
    graph.add_node("create_pr", create_pr_node)
    graph.add_node("cleanup", cleanup_node)

    graph.add_edge(START, "guardrails")
    graph.add_conditional_edges(
        "guardrails",
        should_continue_after_guardrails,
        {"repo_analysis": "repo_analysis", "cleanup": "cleanup"},
    )

    graph.add_edge("repo_analysis", "complexity_assessment")
    graph.add_conditional_edges(
        "complexity_assessment",
        should_use_planner_path,
        {"planner": "planner", "routing_direct": "routing_direct"},
    )

    graph.add_edge("planner", "man_in_the_loop")
    graph.add_conditional_edges(
        "man_in_the_loop",
        should_continue_after_man_in_the_loop,
        {"plan_confirmed": "plan_confirmed", "cleanup": "cleanup"},
    )
    graph.add_edge("plan_confirmed", "dag_execution")
    graph.add_edge("dag_execution", "execution")

    graph.add_edge("routing_direct", "user_feedback")
    graph.add_edge("execution", "user_feedback")

    graph.add_conditional_edges(
        "user_feedback",
        should_create_pr_after_feedback,
        {"create_pr": "create_pr", "cleanup": "cleanup"},
    )

    graph.add_edge("create_pr", "cleanup")
    graph.add_edge("cleanup", END)

    return graph


def compile_orchestrator():
    return build_orchestrator_graph().compile()


_compiled_graph = None


def get_compiled_graph():
    global _compiled_graph
    if _compiled_graph is None:
        _compiled_graph = compile_orchestrator()
    return _compiled_graph


def run_orchestrator(
    user_prompt: str,
    repository_path: str = None,
    github_url: str = None,
    create_pr: bool = False,
    branch_name: str = "",
    pr_title: str = "Auto-generated changes from Orchestrator",
    pr_body: str = "Generated by Orchestrator Agent with AI-powered DevOps automation",
    execution_plan: dict = None,
    plan_only: bool = False,
    skip_planner: bool = False,
    planner_enabled: bool = True,
    planner_complexity_threshold: int = 4,
    user_feedback: str = "accept",
) -> dict:
    initial_state = create_initial_state(
        user_prompt=user_prompt,
        repository_path=repository_path,
        github_url=github_url,
    )

    initial_state["create_pr"] = create_pr
    initial_state["branch_name"] = branch_name
    initial_state["pr_title"] = pr_title
    initial_state["pr_body"] = pr_body
    initial_state["plan_only"] = plan_only
    initial_state["skip_planner"] = skip_planner
    initial_state["planner_enabled"] = planner_enabled
    initial_state["planner_complexity_threshold"] = planner_complexity_threshold
    initial_state["user_feedback"] = user_feedback

    if execution_plan:
        initial_state["approved_execution_plan"] = execution_plan

    final_state = get_compiled_graph().invoke(initial_state)
    return state_to_legacy_format(final_state)


def visualize_graph():
    graph = build_orchestrator_graph()
    try:
        return graph.get_graph().draw_mermaid()
    except Exception:
        return "Graph visualization not available"

